default: &default
  consumer_key: 'YOUR CONSUMER KEY'
  consumer_secret: 'YOUR CONSMER SECRET'
  oauth_token: 'YOUT OAUTH TOKEN'
  oauth_token_secret: 'YOUT OAUTH TOKEN SECRET'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
